#!/usr/bin/env perl
# PODNAME: collector
our $VERSION = '0.001';

=head1 NAME

collector -- Entrypoint for the CPAN Testers Collector service

=head1 SYNOPSIS

  collector daemon
  collector help

=head1 DESCRIPTION

This program loads the CPAN Testers Collector, a L<Mojolicious> web
application. For more detailed help, see C<collector help>.

=head1 SEE ALSO

L<CPAN::Testers::Collector>, L<Mojolicious>

=cut

use strict;
use warnings;
use File::Spec::Functions qw( catdir updir );
use FindBin ();
use lib "$FindBin::Bin/../lib";

require Mojolicious::Commands;
Mojolicious::Commands->start_app( 'CPAN::Testers::Collector' );
